# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$script = <<-'SCRIPT'

# 로케일 및 시간 설정
sudo localedef -v -c -i ko_KR -f UTF-8 ko_KR.UTF-8
sudo localectl set-locale LANG=ko_KR.utf8
sudo timedatectl set-timezone Asia/Seoul

# 데몬별 필요한 파일 옮기기 
sudo /bin/mv -f /home/vagrant/ntp.conf /etc/ntp.conf
sudo /bin/mv -f /home/vagrant/resolv.conf /etc/resolv.conf
sudo /bin/mv -f /home/vagrant/nginx.conf /etc/nginx/nginx.conf
sudo /bin/mv -f /home/vagrant/default /etc/nginx/sites-available/default

# ntpd 데몬 활성화
sudo systemctl enable --now ntp

# git 설정
sudo git config --global user.name "gangdonguri"
sudo git config --global user.email "rhkdgnsvk2@gmail.com"
chmod 400 /home/vagrant/.ssh/id_ed25519

# nvm 설치
sudo wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

SCRIPT

Vagrant.configure("2") do |config|

  # Define base image
  config.vm.box = "generic/ubuntu1804"

  # ubuntu-Server
  config.vm.define "ubuntu-server" do |ubuntu_server|
    ubuntu_server.vm.hostname = "ubuntu-server"

    # Virtualbox Virtualization
    ubuntu_server.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu_server"
      vb.memory = 4096
      vb.cpus =  2
    end

    # Provisioning
    ubuntu_server.vm.provision "shell", path: "bootstrap.sh", run: "once"
    ubuntu_server.vm.provision "file", source: "./.vimrc", destination: "/home/vagrant/.vimrc"
    ubuntu_server.vm.provision "file", source: "./ntp.conf", destination: "/home/vagrant/ntp.conf"
    ubuntu_server.vm.provision "file", source: "./resolv.conf", destination: "/home/vagrant/resolv.conf"
    ubuntu_server.vm.provision "file", source: "./student.pem", destination: "/home/vagrant/student.pem"
    ubuntu_server.vm.provision "file", source: "./id_ed25519", destination: "/home/vagrant/.ssh/id_ed25519"
    ubuntu_server.vm.provision "file", source: "./nginx.conf", destination: "/home/vagrant/nginx.conf"
    ubuntu_server.vm.provision "file", source: "./default", destination: "/home/vagrant/default"
    ubuntu_server.vm.provision "shell", 
      inline: $script, run: "once"
    
    # Network
    ubuntu_server.vm.network "forwarded_port", guest: 80, host: 80
    ubuntu_server.vm.network "forwarded_port", guest: 443, host: 443
    ubuntu_server.vm.network "forwarded_port", guest: 8080, host: 8080
    ubuntu_server.vm.network "forwarded_port", guest: 8000, host: 8000
    ubuntu_server.vm.network "forwarded_port", guest: 10024, host: 10024
    ubuntu_server.vm.network "public_network", ip: "192.168.0.10"
    ubuntu_server.vm.network "private_network", ip: "192.168.10.10"
  end
end

